### ISSUE TITLE
Cannot read properties of undefined (reading 'deepEqual')

### ISSUE THREAD

**Issue by wrappidcare** [wrappid/wrappid-reported-erros#5]
## Description:
No description provided.
## Steps To Create:
No steps provided.
## Stack trace:
<pre>TypeError: Cannot read properties of undefined (reading 'deepEqual')
    at t.update (https://demo.wrappid.dev/static/js/bundle.js:266853:21)
    at NativeJSONEditor.jsonEditorValueUpdate (https://demo.wrappid.dev/static/js/bundle.js:217654:25)
    at NativeJSONEditor.componentDidUpdate (https://demo.wrappid.dev/static/js/bundle.js:217641:10)
    at commitLayoutEffectOnFiber (https://demo.wrappid.dev/static/js/bundle.js:313240:34)
    at commitLayoutMountEffects_complete (https://demo.wrappid.dev/static/js/bundle.js:314381:13)
    at commitLayoutEffects_begin (https://demo.wrappid.dev/static/js/bundle.js:314370:11)
    at commitLayoutEffects (https://demo.wrappid.dev/static/js/bundle.js:314316:7)
    at commitRootImpl (https://demo.wrappid.dev/static/js/bundle.js:316225:9)
    at commitRoot (https://demo.wrappid.dev/static/js/bundle.js:316105:9)
    at finishConcurrentRender (https://demo.wrappid.dev/static/js/bundle.js:315502:13)

    at NativeJSONEditor (https://demo.wrappid.dev/static/js/bundle.js:217621:1)
    at CoreJSONEditor
    at CoreFormInputs (https://demo.wrappid.dev/static/js/bundle.js:192175:5)
    at div
    at https://demo.wrappid.dev/static/js/bundle.js:91898:66
    at Grid (https://demo.wrappid.dev/static/js/bundle.js:113316:87)
    at O (https://demo.wrappid.dev/static/js/bundle.js:337999:8)
    at div
    at https://demo.wrappid.dev/static/js/bundle.js:91898:66
    at Grid (https://demo.wrappid.dev/static/js/bundle.js:113316:87)
    at O (https://demo.wrappid.dev/static/js/bundle.js:337999:8)
    at NativeGrid (https://demo.wrappid.dev/static/js/bundle.js:219154:48)
    at CoreGrid (https://demo.wrappid.dev/static/js/bundle.js:193060:53)
    at form
    at NativeFormContainer (https://demo.wrappid.dev/static/js/bundle.js:216006:73)
    at CoreFormContainer (https://demo.wrappid.dev/static/js/bundle.js:191843:94)
    at Formik (https://demo.wrappid.dev/static/js/bundle.js:235740:19)
    at CoreEditForm (https://demo.wrappid.dev/static/js/bundle.js:190762:35)
    at div
    at https://demo.wrappid.dev/static/js/bundle.js:91898:66
    at Grid (https://demo.wrappid.dev/static/js/bundle.js:113316:87)
    at O (https://demo.wrappid.dev/static/js/bundle.js:337999:8)
    at div
    at https://demo.wrappid.dev/static/js/bundle.js:91898:66
    at Grid (https://demo.wrappid.dev/static/js/bundle.js:113316:87)
    at O (https://demo.wrappid.dev/static/js/bundle.js:337999:8)
    at NativeGrid (https://demo.wrappid.dev/static/js/bundle.js:219154:48)
    at CoreGrid (https://demo.wrappid.dev/static/js/bundle.js:193060:53)
    at CoreForm (https://demo.wrappid.dev/static/js/bundle.js:190987:1)
    at ConnectFunction (https://demo.wrappid.dev/static/js/bundle.js:320375:114)
    at div
    at https://demo.wrappid.dev/static/js/bundle.js:91898:66
    at CardContent (https://demo.wrappid.dev/static/js/bundle.js:106000:82)
    at O (https://demo.wrappid.dev/static/js/bundle.js:337999:8)
    at NativeCardContent (https://demo.wrappid.dev/static/js/bundle.js:220194:95)
    at CoreCardContent (https://demo.wrappid.dev/static/js/bundle.js:196125:53)
    at div
    at https://demo.wrappid.dev/static/js/bundle.js:91898:66
    at Paper (https://demo.wrappid.dev/static/js/bundle.js:124158:83)
    at https://demo.wrappid.dev/static/js/bundle.js:91898:66
    at Card (https://demo.wrappid.dev/static/js/bundle.js:105481:82)
    at O (https://demo.wrappid.dev/static/js/bundle.js:337999:8)
    at NativeCard (https://demo.wrappid.dev/static/js/bundle.js:220110:166)
    at CoreCard (https://demo.wrappid.dev/static/js/bundle.js:195999:53)
    at NativeDataTableDetailsPaneContainer (https://demo.wrappid.dev/static/js/bundle.js:215533:16)
    at CoreDataTableDetailsPaneContainer (https://demo.wrappid.dev/static/js/bundle.js:182820:110)
    at CoreDataTableDetailsPane (https://demo.wrappid.dev/static/js/bundle.js:182590:5)
    at div
    at https://demo.wrappid.dev/static/js/bundle.js:91898:66
    at Grid (https://demo.wrappid.dev/static/js/bundle.js:113316:87)
    at O (https://demo.wrappid.dev/static/js/bundle.js:337999:8)
    at div
    at https://demo.wrappid.dev/static/js/bundle.js:91898:66
    at Grid (https://demo.wrappid.dev/static/js/bundle.js:113316:87)
    at O (https://demo.wrappid.dev/static/js/bundle.js:337999:8)
    at NativeGrid (https://demo.wrappid.dev/static/js/bundle.js:219154:48)
    at CoreGrid (https://demo.wrappid.dev/static/js/bundle.js:193060:53)
    at CoreDataTable (https://demo.wrappid.dev/static/js/bundle.js:181683:48)
    at div
    at https://demo.wrappid.dev/static/js/bundle.js:91898:66
    at Box (https://demo.wrappid.dev/static/js/bundle.js:150378:72)
    at O (https://demo.wrappid.dev/static/js/bundle.js:337999:8)
    at NativeBox
    at https://demo.wrappid.dev/static/js/bundle.js:192955:53
    at main
    at https://demo.wrappid.dev/static/js/bundle.js:91898:66
    at Box (https://demo.wrappid.dev/static/js/bundle.js:150378:72)
    at O (https://demo.wrappid.dev/static/js/bundle.js:337999:8)
    at NativeBox
    at div
    at https://demo.wrappid.dev/static/js/bundle.js:91898:66
    at Box (https://demo.wrappid.dev/static/js/bundle.js:150378:72)
    at O (https://demo.wrappid.dev/static/js/bundle.js:337999:8)
    at NativeBox
    at NativeAppContainer (https://demo.wrappid.dev/static/js/bundle.js:218991:5)
    at LayoutManager (https://demo.wrappid.dev/static/js/bundle.js:202294:5)
    at div
    at https://demo.wrappid.dev/static/js/bundle.js:91898:66
    at Box (https://demo.wrappid.dev/static/js/bundle.js:150378:72)
    at O (https://demo.wrappid.dev/static/js/bundle.js:337999:8)
    at NativeBox
    at https://demo.wrappid.dev/static/js/bundle.js:192955:53
    at div
    at https://demo.wrappid.dev/static/js/bundle.js:91898:66
    at Box (https://demo.wrappid.dev/static/js/bundle.js:150378:72)
    at O (https://demo.wrappid.dev/static/js/bundle.js:337999:8)
    at NativeBox
    at NativePageContainer (https://demo.wrappid.dev/static/js/bundle.js:219385:5)
    at DefaultPropsProvider (https://demo.wrappid.dev/static/js/bundle.js:148589:3)
    at RtlProvider (https://demo.wrappid.dev/static/js/bundle.js:148806:7)
    at ThemeProvider (https://demo.wrappid.dev/static/js/bundle.js:147457:5)
    at ThemeProvider (https://demo.wrappid.dev/static/js/bundle.js:149097:5)
    at ThemeProvider (https://demo.wrappid.dev/static/js/bundle.js:144697:14)
    at NativeThemeProvider (https://demo.wrappid.dev/static/js/bundle.js:223967:45)
    at CoreThemeProvider (https://demo.wrappid.dev/static/js/bundle.js:208385:53)
    at StylesProvider (https://demo.wrappid.dev/static/js/bundle.js:224285:5)
    at ErrorBoundary (https://demo.wrappid.dev/static/js/bundle.js:202912:5)
    at PageContainer (https://demo.wrappid.dev/static/js/bundle.js:202689:48)
    at Routes (https://demo.wrappid.dev/static/js/bundle.js:323689:5)
    at CoreRoutes (https://demo.wrappid.dev/static/js/bundle.js:175652:35)
    at Router (https://demo.wrappid.dev/static/js/bundle.js:323629:15)
    at BrowserRouter (https://demo.wrappid.dev/static/js/bundle.js:322561:5)
    at NativeNavigation (https://demo.wrappid.dev/static/js/bundle.js:219749:5)
    at CoreNavigation (https://demo.wrappid.dev/static/js/bundle.js:194928:90)
    at div
    at O (https://demo.wrappid.dev/static/js/bundle.js:337999:8)
    at NativeAppDiv (https://demo.wrappid.dev/static/js/bundle.js:219030:85)
    at CoreAppDiv (https://demo.wrappid.dev/static/js/bundle.js:192905:53)
    at DefaultPropsProvider (https://demo.wrappid.dev/static/js/bundle.js:148589:3)
    at RtlProvider (https://demo.wrappid.dev/static/js/bundle.js:148806:7)
    at ThemeProvider (https://demo.wrappid.dev/static/js/bundle.js:147457:5)
    at ThemeProvider (https://demo.wrappid.dev/static/js/bundle.js:149097:5)
    at ThemeProvider (https://demo.wrappid.dev/static/js/bundle.js:144697:14)
    at NativeThemeProvider (https://demo.wrappid.dev/static/js/bundle.js:223967:45)
    at CoreThemeProvider (https://demo.wrappid.dev/static/js/bundle.js:208385:53)
    at CoreRoutesProvider (https://demo.wrappid.dev/static/js/bundle.js:203467:13)
    at CoreContextProvider (https://demo.wrappid.dev/static/js/bundle.js:203675:5)
    at StylesProvider (https://demo.wrappid.dev/static/js/bundle.js:224285:5)
    at PersistGate (https://demo.wrappid.dev/static/js/bundle.js:334723:5)
    at Provider (https://demo.wrappid.dev/static/js/bundle.js:320106:3)
    at CoreProvider (https://demo.wrappid.dev/static/js/bundle.js:203791:5)
    at WrappidSyncer (https://demo.wrappid.dev/static/js/bundle.js:224712:3)
    at CoreAppStrictWrapper (https://demo.wrappid.dev/static/js/bundle.js:175596:5)
    at CoreApp (https://demo.wrappid.dev/static/js/bundle.js:175530:5)
    at App</pre>
## Developer Information:
| Key | Value |
|---|---|
| Frontend URL | https://demo.wrappid.dev/database/editor |
| Frontend Version | 0.0.568 |
| Backend URL | undefined |
| Backend Version | N/A |
| User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 |
| Device | Browser |
| Browser | Brave Ver: 130.0.0.0 |
| OS | Linux Ver: x86_64 |
## Reporter Information:
| Key | Value |
|---|---|
| Name | Unnamed |
| Email | undefined |
| Phone | undefined |
| Role | system_admin |
| Creation Time | 10/20/2024, 4:53:56 PM |

**Comment by wrappidcare** [comment]
## Description:
No description provided.
## Steps To Create:
No steps provided.
## Stack trace:
Same as above
## Developer Information:
| Key | Value |
|---|---|
| Frontend URL | https://demo.wrappid.dev/database/editor |
| Frontend Version | 0.0.568 |
| Backend URL | undefined |
| Backend Version | N/A |
| User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 |
| Device | Browser |
| Browser | Brave Ver: 130.0.0.0 |
| OS | Linux Ver: x86_64 |
## Reporter Information:
| Key | Value |
|---|---|
| Name | Unnamed |
| Email | undefined |
| Phone | undefined |
| Role | system_admin |
| Creation Time | 10/20/2024, 4:53:56 PM |

**Comment by wrappidcare** [comment]
## Description:
No description provided.
## Steps To Create:
No steps provided.
## Stack trace:
Same as above
## Developer Information:
| Key | Value |
|---|---|
| Frontend URL | https://demo.wrappid.dev/database/editor |
| Frontend Version | 0.0.568 |
| Backend URL | undefined |
| Backend Version | N/A |
| User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 |
| Device | Browser |
| Browser | Brave Ver: 130.0.0.0 |
| OS | Linux Ver: x86_64 |
## Reporter Information:
| Key | Value |
|---|---|
| Name | Unnamed |
| Email | undefined |
| Phone | undefined |
| Role | system_admin |
| Creation Time | 10/20/2024, 4:53:56 PM |

**Comment by wrappidcare** [comment]
## Description:
No description provided.
## Steps To Create:
No steps provided.
## Stack trace:
Same as above
## Developer Information:
| Key | Value |
|---|---|
| Frontend URL | https://demo.wrappid.dev/database/editor |
| Frontend Version | 0.0.568 |
| Backend URL | undefined |
| Backend Version | N/A |
| User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 |
| Device | Browser |
| Browser | Brave Ver: 130.0.0.0 |
| OS | Linux Ver: x86_64 |
## Reporter Information:
| Key | Value |
|---|---|
| Name | Unnamed |
| Email | undefined |
| Phone | undefined |
| Role | system_admin |
| Creation Time | 10/20/2024, 4:53:56 PM |

**Comment by wrappidcare** [comment]
## Description:
No description provided.
## Steps To Create:
No steps provided.
## Stack trace:
Same as above
## Developer Information:
| Key | Value |
|---|---|
| Frontend URL | https://demo.wrappid.dev/database/editor |
| Frontend Version | 0.0.568 |
| Backend URL | undefined |
| Backend Version | N/A |
| User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 |
| Device | Browser |
| Browser | Brave Ver: 130.0.0.0 |
| OS | Linux Ver: x86_64 |
## Reporter Information:
| Key | Value |
|---|---|
| Name | Unnamed |
| Email | undefined |
| Phone | undefined |
| Role | system_admin |
| Creation Time | 10/20/2024, 4:53:56 PM |

**Comment by wrappidcare** [comment]
## Description:
No description provided.
## Steps To Create:
No steps provided.
## Stack trace:
Same as above
## Developer Information:
| Key | Value |
|---|---|
| Frontend URL | https://demo.wrappid.dev/database/editor |
| Frontend Version | 0.0.568 |
| Backend URL | undefined |
| Backend Version | N/A |
| User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 |
| Device | Browser |
| Browser | Brave Ver: 130.0.0.0 |
| OS | Linux Ver: x86_64 |
## Reporter Information:
| Key | Value |
|---|---|
| Name | Unnamed |
| Email | undefined |
| Phone | undefined |
| Role | system_admin |
| Creation Time | 10/20/2024, 4:53:56 PM |
